# For installation run: 
## ansible-galaxy collection install community.crypto

---
- name: URL SSL Certificate Audit
  hosts: localhost
  vars_files: 
    - "vars/url_list.yml"
    - "vars/mail_list.yml"
  tasks:


    - name: INIT DIAGNOSTICS FILE --2
      ansible.builtin.file:
        path: /opt/ansible/daily_check/cert_diag.txt
        state: touch
        group: secteam
        mode: '0765'

    - name: INIT AUDIT REPORT
      lineinfile:
        path: /opt/ansible/daily_check/cert_diag.txt
        line: "Daily Check Summary"

    - name: PERFORM SERVER HANDSHAKE
      community.crypto.get_certificate:
        host: '{{ item.url }}'
        port: '{{ item.port }}'
      delegate_to: localhost
      run_once: true
      register: cert_info
      ignore_errors: yes
      loop: "{{ handshake_list }}"
          
    - name: DOCUMENT SSL
      lineinfile:
        path: /opt/ansible/daily_check/cert_diag.txt
        line: " - NAME/ URL: {{ cert_name }}\n   EXPIRATION: {{ date_of_expire }} --> {{ expire_days }} days\n   ISSUER: {{ issuer }}\n"
        #line: "{{ expire_days }}, {{ issuer }}, {{ cert_name }}"
      vars:
        expire_days: "{{ (( item.not_after | to_datetime('%Y%m%d%H%M%SZ')) - (ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ')) ).days }}"
        date_of_expire: "{{ ( item.not_after | to_datetime('%Y%m%d%H%M%SZ')) }}"
        cert_name: "{{ (item.item).url }}"
        issuer: "{{ (item.issuer).CN }}"
        port_number: "{{ (item.item).port }}"
      with_items: "{{ cert_info.results }}"
      when: item.failed == false
      # ignore_errors: yes

    - name: DOCUMENT INVALID SSL
      lineinfile:
        path: /opt/ansible/daily_check/cert_diag.txt
        line: "FAILED_OPERATION, NULL, {{ cert_name }}, {{ port_number }}\n"
      vars:
        cert_name: "{{ (item.item).url }}"
        port_number: "{{ (item.item).port }}"
      with_items: "{{ cert_info.results }}"
      when: item.failed == true
      # ignore_errors: yes

    - name: EMAIL SSL AUDIT LIST
      mail:
        host: localhost
        port: 25
        to: "{{ item.email }}"
        subject: Daily-Check Certificate Audit
        body: "{{ lookup('file', '/opt/ansible/daily_check/cert_diag.txt') }}"
      loop: "{{ mail_list }}"

    - name: Delete Diagnostics File
      ansible.builtin.file:
        path: /opt/ansible/daily_check/cert_diag.txt
        state: absent

